### ISSUE TITLE
XorW with SDDM....

### ISSUE THREAD

**Issue by mcoyle1960** [pedemonte/gnome-shell-extension-xorwayland#1]
FYI:

Installed SDDM to play around. 
Selected Wayland on login. 

"loginctl show-session 3 -p Type" confirms Wayland, but your extension reports X in the menu.

**Comment by pedemonte** [comment]
@mcoyle1960 : don't know what the issue with SDDM is, but I've changed the way the extension detects the environment it is running on. Would you please try again with the new release?

**Comment by mcoyle1960** [comment]
Fixed with new release! 
What took you so long? :-)

Thanks for being so responsive and creating this useful extension.
